#!/bin/bash
# fragle_quick_start.sh - One-liner demos for each mode

echo ""
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                                                               ║"
echo "║     🎭  FRAGLE THEATRE v2.0 - QUICK START GUIDE  🎭          ║"
echo "║                                                               ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""

echo "DEMO 1: SHELL THEATRE (Terminal-Only, No Dependencies)"
echo "───────────────────────────────────────────────────────"
echo "Command: cd ~/fragle && bash fragle_tui.sh"
echo "What you get:"
echo "  • 🎭 Persona-aware interactive menu"
echo "  • 📖 Lore & history browsing"
echo "  • 🔮 Cosmic Oracle jokes"
echo "  • 🎪 Full theatrical experience in your terminal"
echo "  • ✨ 100% pure bash chaos"
echo ""
echo "Try it: bash fragle_tui.sh"
echo ""

echo "DEMO 2: WEB THEATRE (Browser Experience)"
echo "───────────────────────────────────────"
echo "Commands:"
echo "  npm install          # First time only"
echo "  npm start            # Start server"
echo "  Open: http://localhost:3000"
echo ""
echo "What you get:"
echo "  • 🌐 Beautiful web UI (glitch animations, chaos)"
echo "  • 🎨 Level selection with cards"
echo "  • 📊 Progress bars & trap mechanics"
echo "  • 💫 WebSocket real-time updates"
echo "  • 🔮 Oracle in the browser"
echo "  • 📱 Responsive design (desktop + mobile)"
echo ""
echo "Features:"
echo "  - Persona detection (browser environment signals)"
echo "  - Theatrical animations (glitch, pulse, float)"
echo "  - Dark theme with neon chaos"
echo "  - Keyboard shortcuts (Escape to close traps)"
echo ""

echo "DEMO 3: ELECTRON DESKTOP APP (.app)"
echo "────────────────────────────────────"
echo "Commands:"
echo "  npm install           # First time only"
echo "  npm run electron      # Launch app"
echo ""
echo "What you get:"
echo "  • 💻 Native macOS/Windows/Linux application"
echo "  • 🎪 Full web UI in a desktop window"
echo "  • 📋 Native menu bar (File, Edit, View, Theatre)"
echo "  • ⌨️  Keyboard shortcuts (Cmd+M, Cmd+O)"
echo "  • 🚀 Dev tools toggle (Cmd+Shift+I)"
echo "  • 📦 Can be packaged as .app/.exe/.dmg/.AppImage"
echo ""
echo "Build for distribution:"
echo "  npm run build  # Creates dist/ folder with installers"
echo ""

echo "DEMO 4: ALL AT ONCE (Maximum Chaos)"
echo "───────────────────────────────────"
echo "Command: bash fragle_start.sh all"
echo ""
echo "What happens:"
echo "  1. Web server starts (localhost:3000)"
echo "  2. Electron app opens (native window)"
echo "  3. Shell TUI runs (foreground interaction)"
echo "  4. All three run simultaneously"
echo "  5. Exit shell to stop everything"
echo ""

echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
echo "🎭 THE THEATRE AWAITS YOUR CHOICE 🎭"
echo ""
echo "Quickest path: bash fragle_tui.sh"
echo "Web path: npm install && npm start"
echo "Desktop path: npm install && npm run electron"
echo "Full chaos: bash fragle_start.sh all"
echo ""
echo "═══════════════════════════════════════════════════════════════"
echo ""
